config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :shingle, only: [:index], path: '/'
  post '/' => 'shingle#index', as: 'root'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shingle.rb
require 'net/http'
class Shingle
  class << self
  	def get(url)
  	  uri = URI.parse(url)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      request = Net::HTTP::Get.new(uri.request_uri)
      http.request(request)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/shingle_controller.rb
# frozen_string_literal: true

require 'json'

class ShingleController < ApplicationController
  # API_BASE_URL = "https://mdms.owenscorning.com/api/v1/product/shingles?zip=43659"
  def index
    if params.key?(:zip)
      url = (ENV['API_BASE']).to_s + params[:zip] # specifying json format in the URl
      @shingle_active = 0
      @shingle_active = params[:shingle_active] if params.key?(:shingle_active)
      response = Shingle.get(url)
      s = JSON.parse(response.body, symbolize_names: true)
      if response['status'] == '200 OK'
        @all_shingles = s
        @zip = params[:zip]
        @shingle = if params.key?(:shingle)
                     find_uid(s, params[:shingle])
                   else
                     find_uid(s, 'trudefinition-duration')
                   end
      else
        flash[:error] = 'Zip is not valid'
        render 'zip_form'
      end
    else
      flash[:error] = ''
      render 'zip_form'
    end
  end

  def find_uid(s, str)
    s.find { |h1| h1[:uid] == str }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ocs2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-color'>        
    <%= yield %>
  </body>
</html>

app/views/shingle/_image_gallery.html.erb
<div id="myGallery" class="carousel slide myGallery" data-ride="carousel">
    <div class="carousel-inner">
    <% shingle[:gallery_images].each_with_index do |image,index| %>      
        <div class="item <%= index.to_i == shingle_active.to_i ? 'active' : '' %>">   
            <%= image_tag image[:img_url] , {class:'d-block w-100'} %>
        </div>
    <% end %>
    </div>
<a class="previous round event-cap" href="#myGallery" role="button" data-slide="prev"><
  <span class="sr-only">Previous</span>
</a>
<a class="next round event-cap" href="#myGallery" role="button" data-slide="next">>
  <span class="sr-only">Next</span>
</a>
<div class="container">
    <ol class="carousel-indicators">
    <% shingle[:gallery_images].each_with_index do |image,index| %>
    <li data-target="#myGallery" data-slide-to="<%= index %>" class="<%= index.to_i == shingle_active.to_i ? 'active' : '' %>">
        <%= image_tag image[:img_url] , {class:'img-responsive'} %>
        <span class="image_name"><%= image[:name] %></span>        
    </li>
    <% end %>
    </ol>
    </div>
</div> 

app/views/shingle/_shingle_dropdown.html.erb
<%if all_shingles.present? %> 
<%= form_tag shingle_index_path(),:method=>:get,:id=> 'shingleFrm'  do %>
    <div class="form-group"> 
           <%if zip.present? %> 
              <%= hidden_field_tag 'zip',zip %>   
            <% end %>
            <%= label_tag(:shingle_line, "SHINGLE LINE:") %>
            <%= select_tag("shingle", options_for_select(all_shingles.map {|name| [name[:name],name[:uid]]},shingle[:uid]),
            class: 'form-control',
            id: 'shingles_dropdown')%>      
    </div>
    <% end %>
    <div class="dyn-name">
       <span id = "shingle_group_name" uid-data="<%= shingle[:uid] %>"><%= shingle[:name].upcase %></span>
       <span id="shingleName"></span>
    </div>
<% end %>

app/views/shingle/index.html.erb
<%if @shingle.present? %>
  <div class='container'> 
   <%= link_to('MAIN PAGE',shingle_index_path(),:class=>'menu_zip') %>
    <div class='row'>
      <div id = "shingleReplace">
        <div class="col-md-6">
           <%= render partial: "image_gallery", locals: {shingle: @shingle,shingle_active:@shingle_active} %>         
        </div>
        <div class="col-md-4">
           <%= render partial: "shingle_dropdown", locals: {shingle: @shingle,all_shingles:@all_shingles,zip:@zip} %>   
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shingle/zip_form.html.erb
<div class= "container">
  <div class= "row">
  <% if flash[:error] %>
        <p class="error"><%= flash[:error] %></p>
  <% end %>
  <%= form_tag shingle_index_path(), :method=>:get,:class => 'form-inline zip-mgn' do %>
      
       <%= label_tag "zip","Zip Code" %>
       <%= text_field_tag "zip",nil,:placeholder=> "Enter Zip Code ", :class=>"form-control" ,:required=> true%>  
       <%= submit_tag "Submit", :name=>nil,:class=> "btn btn-primary" %> 
  <% end %>
  </div>
</div>